# Marcus Grant's ZSH Configuration
# Parts of this may be generated by my role-mydotfiles ansible role

# The following lines were added by compinstall
# General ZSH Settings
# ===============================
# Completions
zstyle ':completion:*' format 'Completing %d'
zstyle :compinstall filename "$DOTSDIRZ/.zshrc"

# Compinit autogen'd
autoload -Uz compinit
compinit

# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=1000
# End of lines configured by zsh-newuser-install

# Before continuing because of unpredicatability of zsh config file calls...
# make sure that zshenv has been sourced and its vars have definitions
if [ -z $DOTSDIR ]; then source ~/.zshenv; fi

# Key timeouts
# I set this because vim/nvim feels sluggish in ZSH.
# ZSH apparently treats escape chars differently so needs some tweaking.
KEYTIMEOUT=1 # 1 = 10ms delay for escape chars

# To debug here's a good place to echo out some messages
echo "Path in zshrc is: $PATH"

### Prompt
source "$DOTSDIRZ/prompt.zsh"

### Aliases
source "$DOTSDIRZ/aliases.zsh"

### Plugins
source $DOTSDIRZPLUG/fzf.zsh
source $DOTSDIRZPLUG/gopass.zsh
source $DOTSDIRZPLUG/pyenv.zsh

### PATH overrides - only some of these are needed to make some occur first
# Homebew should default to /opt/homebrew/bin first
# [[ ! $PATH == *"/opt/homebrew/bin"* ]] && export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"


##### Exports (many of these go in zshenv & zprofile)
export TERM="xterm-256color" # Terminal Settings

# Remove duplicates in PATH
typeset -U PATH
